"""add database

Revision ID: 7db40825bdb3
Revises: a4b0c3eaecb7
Create Date: 2018-05-29 16:23:20.933365

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7db40825bdb3'
down_revision = 'a4b0c3eaecb7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('delivery',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.SmallInteger(), nullable=True),
    sa.Column('response', sa.String(length=256), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['job.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('company', sa.Column('about', sa.String(length=1024), nullable=True))
    op.add_column('company', sa.Column('contact', sa.String(length=24), nullable=False))
    op.add_column('company', sa.Column('email', sa.String(length=24), nullable=False))
    op.add_column('company', sa.Column('slug', sa.String(length=24), nullable=False))
    op.add_column('company', sa.Column('stack', sa.String(length=128), nullable=True))
    op.add_column('company', sa.Column('tags', sa.String(length=128), nullable=True))
    op.add_column('company', sa.Column('team_introduction', sa.String(length=256), nullable=True))
    op.add_column('company', sa.Column('user_id', sa.Integer(), nullable=True))
    op.add_column('company', sa.Column('welfares', sa.String(length=256), nullable=True))
    op.create_index(op.f('ix_company_slug'), 'company', ['slug'], unique=True)
    op.drop_constraint('company_ibfk_2', 'company', type_='foreignkey')
    op.drop_constraint('company_ibfk_1', 'company', type_='foreignkey')
    op.create_foreign_key(None, 'company', 'user', ['user_id'], ['id'], ondelete='SET NULL')
    op.drop_column('company', 'required_job_number')
    op.drop_column('company', 'applicants_id')
    op.drop_column('company', 'job_id')
    op.add_column('job', sa.Column('company_id', sa.Integer(), nullable=True))
    op.add_column('job', sa.Column('degree_requirement', sa.String(length=32), nullable=True))
    op.add_column('job', sa.Column('experience_requirement', sa.String(length=256), nullable=True))
    op.add_column('job', sa.Column('is_fulltime', sa.Boolean(), nullable=True))
    op.add_column('job', sa.Column('is_open', sa.Boolean(), nullable=True))
    op.add_column('job', sa.Column('location', sa.String(length=64), nullable=True))
    op.add_column('job', sa.Column('name', sa.String(length=64), nullable=True))
    op.add_column('job', sa.Column('salary_high', sa.Integer(), nullable=False))
    op.add_column('job', sa.Column('salary_low', sa.Integer(), nullable=False))
    op.add_column('job', sa.Column('tags', sa.String(length=128), nullable=True))
    op.add_column('job', sa.Column('views_count', sa.Integer(), nullable=True))
    op.drop_index('ix_job_jobname', table_name='job')
    op.create_foreign_key(None, 'job', 'company', ['company_id'], ['id'], ondelete='CASCADE')
    op.drop_column('job', 'salary_range')
    op.drop_column('job', 'job_location')
    op.drop_column('job', 'experience')
    op.drop_column('job', 'jobname')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job', sa.Column('jobname', mysql.VARCHAR(length=64), nullable=True))
    op.add_column('job', sa.Column('experience', mysql.VARCHAR(length=256), nullable=False))
    op.add_column('job', sa.Column('job_location', mysql.VARCHAR(length=64), nullable=False))
    op.add_column('job', sa.Column('salary_range', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'job', type_='foreignkey')
    op.create_index('ix_job_jobname', 'job', ['jobname'], unique=True)
    op.drop_column('job', 'views_count')
    op.drop_column('job', 'tags')
    op.drop_column('job', 'salary_low')
    op.drop_column('job', 'salary_high')
    op.drop_column('job', 'name')
    op.drop_column('job', 'location')
    op.drop_column('job', 'is_open')
    op.drop_column('job', 'is_fulltime')
    op.drop_column('job', 'experience_requirement')
    op.drop_column('job', 'degree_requirement')
    op.drop_column('job', 'company_id')
    op.add_column('company', sa.Column('job_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('company', sa.Column('applicants_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('company', sa.Column('required_job_number', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'company', type_='foreignkey')
    op.create_foreign_key('company_ibfk_1', 'company', 'user', ['applicants_id'], ['id'])
    op.create_foreign_key('company_ibfk_2', 'company', 'job', ['job_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_company_slug'), table_name='company')
    op.drop_column('company', 'welfares')
    op.drop_column('company', 'user_id')
    op.drop_column('company', 'team_introduction')
    op.drop_column('company', 'tags')
    op.drop_column('company', 'stack')
    op.drop_column('company', 'slug')
    op.drop_column('company', 'email')
    op.drop_column('company', 'contact')
    op.drop_column('company', 'about')
    op.drop_table('delivery')
    # ### end Alembic commands ###
