"""upgrade model

Revision ID: f3631ad2b7df
Revises: 7db40825bdb3
Create Date: 2018-05-30 16:40:51.153223

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f3631ad2b7df'
down_revision = '7db40825bdb3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_detail',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('slug', sa.String(length=24), nullable=False),
    sa.Column('logo', sa.String(length=256), nullable=False),
    sa.Column('contact', sa.String(length=24), nullable=False),
    sa.Column('email', sa.String(length=24), nullable=False),
    sa.Column('website', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=256), nullable=True),
    sa.Column('location', sa.String(length=32), nullable=False),
    sa.Column('about', sa.String(length=1024), nullable=True),
    sa.Column('tags', sa.String(length=128), nullable=True),
    sa.Column('stack', sa.String(length=128), nullable=True),
    sa.Column('team_introduction', sa.String(length=256), nullable=True),
    sa.Column('welfares', sa.String(length=256), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_detail_name'), 'company_detail', ['name'], unique=True)
    op.create_index(op.f('ix_company_detail_slug'), 'company_detail', ['slug'], unique=True)
    op.drop_index('ix_company_name', table_name='company')
    op.drop_index('ix_company_slug', table_name='company')
    op.drop_table('company')
    op.drop_constraint('job_ibfk_2', 'job', type_='foreignkey')
    op.create_foreign_key(None, 'job', 'user', ['company_id'], ['id'], ondelete='CASCADE')
    op.drop_column('job', 'job_requirement')
    op.drop_column('job', 'publish_time')
    op.drop_column('job', 'job_description')
    op.add_column('user', sa.Column('resume_url', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'resume_url')
    op.add_column('job', sa.Column('job_description', mysql.VARCHAR(length=256), nullable=False))
    op.add_column('job', sa.Column('publish_time', mysql.VARCHAR(length=32), nullable=False))
    op.add_column('job', sa.Column('job_requirement', mysql.VARCHAR(length=256), nullable=False))
    op.drop_constraint(None, 'job', type_='foreignkey')
    op.create_foreign_key('job_ibfk_2', 'job', 'company', ['company_id'], ['id'], ondelete='CASCADE')
    op.create_table('company',
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('logo', mysql.VARCHAR(length=256), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('website', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('description', mysql.VARCHAR(length=256), nullable=True),
    sa.Column('location', mysql.VARCHAR(length=32), nullable=False),
    sa.Column('about', mysql.VARCHAR(length=1024), nullable=True),
    sa.Column('contact', mysql.VARCHAR(length=24), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=24), nullable=False),
    sa.Column('slug', mysql.VARCHAR(length=24), nullable=False),
    sa.Column('stack', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('tags', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('team_introduction', mysql.VARCHAR(length=256), nullable=True),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('welfares', mysql.VARCHAR(length=256), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='company_ibfk_1', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_company_slug', 'company', ['slug'], unique=True)
    op.create_index('ix_company_name', 'company', ['name'], unique=True)
    op.drop_index(op.f('ix_company_detail_slug'), table_name='company_detail')
    op.drop_index(op.f('ix_company_detail_name'), table_name='company_detail')
    op.drop_table('company_detail')
    # ### end Alembic commands ###
